#ifndef __DBG_UTIL_ERR_H__
#define __DBG_UTIL_ERR_H__

// error codes
#define DBGUTIL_ERR_OK 0
#define DBGUTIL_ERR_NOMEM 1
#define DBGUTIL_ERR_INVALID_ARGUMENT 2
#define DBGUTIL_ERR_INVALID_STATE 3
#define DBGUTIL_ERR_RESOURCE_LIMIT 4
#define DBGUTIL_ERR_SYSTEM_FAILURE 5
#define DBGUTIL_ERR_NOT_FOUND 6
#define DBGUTIL_ERR_INTERNAL_ERROR 7
#define DBGUTIL_ERR_EOF 8
#define DBGUTIL_ERR_ALREADY_EXISTS 9
#define DBGUTIL_ERR_ACCESS_DENIED 10
#define DBGUTIL_ERR_END_OF_STREAM 11
#define DBGUTIL_ERR_NOT_IMPLEMENTED 12
#define DBGUTIL_ERR_DATA_CORRUPT 13
#define DBGUTIL_ERR_RESOURCE_BUSY 14

namespace libdbg {

/** @typedef Error type. */
typedef int DbgUtilErr;

}  // namespace libdbg

#endif  // __DBG_UTIL_ERR_H__